# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import starkexpress_api
from starkexpress_api.model.orderbook_level1_data_dto import OrderbookLevel1DataDto
from starkexpress_api import configuration


class TestOrderbookLevel1DataDto(unittest.TestCase):
    """OrderbookLevel1DataDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
