# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import starkexpress_api
from starkexpress_api.model.tenant_asset_dto_paginated_response_dto import TenantAssetDtoPaginatedResponseDto
from starkexpress_api import configuration


class TestTenantAssetDtoPaginatedResponseDto(unittest.TestCase):
    """TenantAssetDtoPaginatedResponseDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
