# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

import unittest

import starkexpress_api
from starkexpress_api.model.orderbook_level2_entry_dto import OrderbookLevel2EntryDto
from starkexpress_api import configuration


class TestOrderbookLevel2EntryDto(unittest.TestCase):
    """OrderbookLevel2EntryDto unit test stubs"""
    _configuration = configuration.Configuration()


if __name__ == '__main__':
    unittest.main()
