# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from starkexpress_api.paths.api_v1_assets_deploy.post import DeployAsset
from starkexpress_api.paths.api_v1_assets.post import EnableAsset
from starkexpress_api.paths.api_v1_assets.get import GetAllAssets
from starkexpress_api.paths.api_v1_assets_asset_id.get import GetAsset


class AssetApi(
    DeployAsset,
    EnableAsset,
    GetAllAssets,
    GetAsset,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
