# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from starkexpress_api.paths.api_v1_fees.post import ConfigureFeeModel
from starkexpress_api.paths.api_v1_fees_fee_id.get import GetFeeModel


class FeeApi(
    ConfigureFeeModel,
    GetFeeModel,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
