# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from starkexpress_api.paths.api_v1_orders_order_id.delete import CancelOrder
from starkexpress_api.paths.api_v1_orders_details.post import OrderDetails
from starkexpress_api.paths.api_v1_orders.post import SubmitOrder


class OrderApi(
    CancelOrder,
    OrderDetails,
    SubmitOrder,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
