# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from starkexpress_api.paths.api_v1_transfers.post import Transfer
from starkexpress_api.paths.api_v1_transfers_details.post import TransferDetails


class TransferApi(
    Transfer,
    TransferDetails,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
