# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from starkexpress_api.paths.api_v1_users_register_details.get import EIp712Details
from starkexpress_api.paths.api_v1_users.get import GetAllUsers
from starkexpress_api.paths.api_v1_users_user_id.get import GetUser
from starkexpress_api.paths.api_v1_users.post import RegisterUser


class UserApi(
    EIp712Details,
    GetAllUsers,
    GetUser,
    RegisterUser,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
