# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from starkexpress_api import schemas  # noqa: F401


class BatchMintRequestModel(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Request model to mint a batch of assets.
    """


    class MetaOapg:
        required = {
            "users",
        }
        
        class properties:
            
            
            class users(
                schemas.ListSchema
            ):
            
            
                class MetaOapg:
                    min_items = 1
                    
                    @staticmethod
                    def items() -> typing.Type['MintRequestDataModel']:
                        return MintRequestDataModel
            
                def __new__(
                    cls,
                    _arg: typing.Union[typing.Tuple['MintRequestDataModel'], typing.List['MintRequestDataModel']],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'users':
                    return super().__new__(
                        cls,
                        _arg,
                        _configuration=_configuration,
                    )
            
                def __getitem__(self, i: int) -> 'MintRequestDataModel':
                    return super().__getitem__(i)
            __annotations__ = {
                "users": users,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    users: MetaOapg.properties.users
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["users"]) -> MetaOapg.properties.users: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["users"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["users"]) -> MetaOapg.properties.users: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["users"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        users: typing.Union[MetaOapg.properties.users, list, tuple, ],
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'BatchMintRequestModel':
        return super().__new__(
            cls,
            *_args,
            users=users,
            _configuration=_configuration,
        )

from starkexpress_api.model.mint_request_data_model import MintRequestDataModel
