# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from starkexpress_api import schemas  # noqa: F401


class ConfigureFeeModel(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Request model to configure the fee model for an operation.
    """


    class MetaOapg:
        required = {
            "basisPoints",
            "feeAction",
        }
        
        class properties:
        
            @staticmethod
            def feeAction() -> typing.Type['FeeAction']:
                return FeeAction
            
            
            class basisPoints(
                schemas.Int32Schema
            ):
                pass
            __annotations__ = {
                "feeAction": feeAction,
                "basisPoints": basisPoints,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    basisPoints: MetaOapg.properties.basisPoints
    feeAction: 'FeeAction'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["basisPoints"]) -> MetaOapg.properties.basisPoints: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["feeAction"]) -> 'FeeAction': ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["basisPoints"], typing_extensions.Literal["feeAction"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["basisPoints"]) -> MetaOapg.properties.basisPoints: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["feeAction"]) -> 'FeeAction': ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["basisPoints"], typing_extensions.Literal["feeAction"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        basisPoints: typing.Union[MetaOapg.properties.basisPoints, decimal.Decimal, int, ],
        feeAction: 'FeeAction',
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'ConfigureFeeModel':
        return super().__new__(
            cls,
            *_args,
            basisPoints=basisPoints,
            feeAction=feeAction,
            _configuration=_configuration,
        )

from starkexpress_api.model.fee_action import FeeAction
