# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from starkexpress_api import schemas  # noqa: F401


class OrderDto(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
            orderId = schemas.UUIDSchema
            orderbookId = schemas.UUIDSchema
            price = schemas.Float64Schema
            originalAmount = schemas.StrSchema
            executedAmount = schemas.StrSchema
            
            
            class fills(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    format = 'array'
                    
                    @staticmethod
                    def items() -> typing.Type['OrderFillDto']:
                        return OrderFillDto
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'fills':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "orderId": orderId,
                "orderbookId": orderbookId,
                "price": price,
                "originalAmount": originalAmount,
                "executedAmount": executedAmount,
                "fills": fills,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["orderId"]) -> MetaOapg.properties.orderId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["orderbookId"]) -> MetaOapg.properties.orderbookId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["price"]) -> MetaOapg.properties.price: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["originalAmount"]) -> MetaOapg.properties.originalAmount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["executedAmount"]) -> MetaOapg.properties.executedAmount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["fills"]) -> MetaOapg.properties.fills: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["orderId"], typing_extensions.Literal["orderbookId"], typing_extensions.Literal["price"], typing_extensions.Literal["originalAmount"], typing_extensions.Literal["executedAmount"], typing_extensions.Literal["fills"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["orderId"]) -> typing.Union[MetaOapg.properties.orderId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["orderbookId"]) -> typing.Union[MetaOapg.properties.orderbookId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["price"]) -> typing.Union[MetaOapg.properties.price, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["originalAmount"]) -> typing.Union[MetaOapg.properties.originalAmount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["executedAmount"]) -> typing.Union[MetaOapg.properties.executedAmount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["fills"]) -> typing.Union[MetaOapg.properties.fills, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["orderId"], typing_extensions.Literal["orderbookId"], typing_extensions.Literal["price"], typing_extensions.Literal["originalAmount"], typing_extensions.Literal["executedAmount"], typing_extensions.Literal["fills"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        orderId: typing.Union[MetaOapg.properties.orderId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        orderbookId: typing.Union[MetaOapg.properties.orderbookId, str, uuid.UUID, schemas.Unset] = schemas.unset,
        price: typing.Union[MetaOapg.properties.price, decimal.Decimal, int, float, schemas.Unset] = schemas.unset,
        originalAmount: typing.Union[MetaOapg.properties.originalAmount, str, schemas.Unset] = schemas.unset,
        executedAmount: typing.Union[MetaOapg.properties.executedAmount, str, schemas.Unset] = schemas.unset,
        fills: typing.Union[MetaOapg.properties.fills, list, tuple, None, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'OrderDto':
        return super().__new__(
            cls,
            *_args,
            orderId=orderId,
            orderbookId=orderbookId,
            price=price,
            originalAmount=originalAmount,
            executedAmount=executedAmount,
            fills=fills,
            _configuration=_configuration,
        )

from starkexpress_api.model.order_fill_dto import OrderFillDto
