# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from starkexpress_api import schemas  # noqa: F401


class RegisterDetailsDto(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def domain() -> typing.Type['DomainDto']:
                return DomainDto
            
            
            class types(
                schemas.DictBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneFrozenDictMixin
            ):
            
            
                class MetaOapg:
                    format = 'dict'
                    
                    
                    class additional_properties(
                        schemas.ListSchema
                    ):
                    
                    
                        class MetaOapg:
                            
                            @staticmethod
                            def items() -> typing.Type['MemberDescriptionDto']:
                                return MemberDescriptionDto
                    
                        def __new__(
                            cls,
                            _arg: typing.Union[typing.Tuple['MemberDescriptionDto'], typing.List['MemberDescriptionDto']],
                            _configuration: typing.Optional[schemas.Configuration] = None,
                        ) -> 'additional_properties':
                            return super().__new__(
                                cls,
                                _arg,
                                _configuration=_configuration,
                            )
                    
                        def __getitem__(self, i: int) -> 'MemberDescriptionDto':
                            return super().__getitem__(i)
            
                
                def __getitem__(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    # dict_instance[name] accessor
                    return super().__getitem__(name)
                
                def get_item_oapg(self, name: typing.Union[str, ]) -> MetaOapg.additional_properties:
                    return super().get_item_oapg(name)
            
                def __new__(
                    cls,
                    *_args: typing.Union[dict, frozendict.frozendict, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                    **kwargs: typing.Union[MetaOapg.additional_properties, list, tuple, ],
                ) -> 'types':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                        **kwargs,
                    )
            
            
            class primaryType(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'string'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'primaryType':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class message(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    format = 'array'
                    
                    @staticmethod
                    def items() -> typing.Type['MemberValueDto']:
                        return MemberValueDto
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'message':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class domainRawValues(
                schemas.ListBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneTupleMixin
            ):
            
            
                class MetaOapg:
                    format = 'array'
                    
                    @staticmethod
                    def items() -> typing.Type['MemberValueDto']:
                        return MemberValueDto
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[list, tuple, None, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'domainRawValues':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "domain": domain,
                "types": types,
                "primaryType": primaryType,
                "message": message,
                "domainRawValues": domainRawValues,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["domain"]) -> 'DomainDto': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["types"]) -> MetaOapg.properties.types: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["primaryType"]) -> MetaOapg.properties.primaryType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["message"]) -> MetaOapg.properties.message: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["domainRawValues"]) -> MetaOapg.properties.domainRawValues: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["domain"], typing_extensions.Literal["types"], typing_extensions.Literal["primaryType"], typing_extensions.Literal["message"], typing_extensions.Literal["domainRawValues"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["domain"]) -> typing.Union['DomainDto', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["types"]) -> typing.Union[MetaOapg.properties.types, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["primaryType"]) -> typing.Union[MetaOapg.properties.primaryType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["message"]) -> typing.Union[MetaOapg.properties.message, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["domainRawValues"]) -> typing.Union[MetaOapg.properties.domainRawValues, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["domain"], typing_extensions.Literal["types"], typing_extensions.Literal["primaryType"], typing_extensions.Literal["message"], typing_extensions.Literal["domainRawValues"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        domain: typing.Union['DomainDto', schemas.Unset] = schemas.unset,
        types: typing.Union[MetaOapg.properties.types, dict, frozendict.frozendict, None, schemas.Unset] = schemas.unset,
        primaryType: typing.Union[MetaOapg.properties.primaryType, None, str, schemas.Unset] = schemas.unset,
        message: typing.Union[MetaOapg.properties.message, list, tuple, None, schemas.Unset] = schemas.unset,
        domainRawValues: typing.Union[MetaOapg.properties.domainRawValues, list, tuple, None, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'RegisterDetailsDto':
        return super().__new__(
            cls,
            *_args,
            domain=domain,
            types=types,
            primaryType=primaryType,
            message=message,
            domainRawValues=domainRawValues,
            _configuration=_configuration,
        )

from starkexpress_api.model.domain_dto import DomainDto
from starkexpress_api.model.member_description_dto import MemberDescriptionDto
from starkexpress_api.model.member_value_dto import MemberValueDto
