# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from starkexpress_api import schemas  # noqa: F401


class SettlementInfoModel(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Settlement details model.
    """


    class MetaOapg:
        
        class properties:
            
            
            class orderAFeeDestinationVaultId(
                schemas.UUIDBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'uuid'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, uuid.UUID, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'orderAFeeDestinationVaultId':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class orderAFeeAmount(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'string'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'orderAFeeAmount':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class orderBFeeDestinationVaultId(
                schemas.UUIDBase,
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'uuid'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, uuid.UUID, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'orderBFeeDestinationVaultId':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class orderBFeeAmount(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'string'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'orderBFeeAmount':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "orderAFeeDestinationVaultId": orderAFeeDestinationVaultId,
                "orderAFeeAmount": orderAFeeAmount,
                "orderBFeeDestinationVaultId": orderBFeeDestinationVaultId,
                "orderBFeeAmount": orderBFeeAmount,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["orderAFeeDestinationVaultId"]) -> MetaOapg.properties.orderAFeeDestinationVaultId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["orderAFeeAmount"]) -> MetaOapg.properties.orderAFeeAmount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["orderBFeeDestinationVaultId"]) -> MetaOapg.properties.orderBFeeDestinationVaultId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["orderBFeeAmount"]) -> MetaOapg.properties.orderBFeeAmount: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["orderAFeeDestinationVaultId"], typing_extensions.Literal["orderAFeeAmount"], typing_extensions.Literal["orderBFeeDestinationVaultId"], typing_extensions.Literal["orderBFeeAmount"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["orderAFeeDestinationVaultId"]) -> typing.Union[MetaOapg.properties.orderAFeeDestinationVaultId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["orderAFeeAmount"]) -> typing.Union[MetaOapg.properties.orderAFeeAmount, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["orderBFeeDestinationVaultId"]) -> typing.Union[MetaOapg.properties.orderBFeeDestinationVaultId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["orderBFeeAmount"]) -> typing.Union[MetaOapg.properties.orderBFeeAmount, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["orderAFeeDestinationVaultId"], typing_extensions.Literal["orderAFeeAmount"], typing_extensions.Literal["orderBFeeDestinationVaultId"], typing_extensions.Literal["orderBFeeAmount"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        orderAFeeDestinationVaultId: typing.Union[MetaOapg.properties.orderAFeeDestinationVaultId, None, str, uuid.UUID, schemas.Unset] = schemas.unset,
        orderAFeeAmount: typing.Union[MetaOapg.properties.orderAFeeAmount, None, str, schemas.Unset] = schemas.unset,
        orderBFeeDestinationVaultId: typing.Union[MetaOapg.properties.orderBFeeDestinationVaultId, None, str, uuid.UUID, schemas.Unset] = schemas.unset,
        orderBFeeAmount: typing.Union[MetaOapg.properties.orderBFeeAmount, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'SettlementInfoModel':
        return super().__new__(
            cls,
            *_args,
            orderAFeeDestinationVaultId=orderAFeeDestinationVaultId,
            orderAFeeAmount=orderAFeeAmount,
            orderBFeeDestinationVaultId=orderBFeeDestinationVaultId,
            orderBFeeAmount=orderBFeeAmount,
            _configuration=_configuration,
        )
