# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from starkexpress_api import schemas  # noqa: F401


class TransferDetailsModel(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Request model to fetch details for a signable transfer.
    """


    class MetaOapg:
        required = {
            "receiverDataAvailabilityMode",
            "amount",
            "senderUserId",
            "assetId",
            "senderDataAvailabilityMode",
            "receiverUserId",
        }
        
        class properties:
            senderUserId = schemas.UUIDSchema
            receiverUserId = schemas.UUIDSchema
            assetId = schemas.UUIDSchema
        
            @staticmethod
            def senderDataAvailabilityMode() -> typing.Type['DataAvailabilityModes']:
                return DataAvailabilityModes
        
            @staticmethod
            def receiverDataAvailabilityMode() -> typing.Type['DataAvailabilityModes']:
                return DataAvailabilityModes
            amount = schemas.StrSchema
            
            
            class tokenId(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'hex'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tokenId':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class mintingBlob(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'hex'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'mintingBlob':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "senderUserId": senderUserId,
                "receiverUserId": receiverUserId,
                "assetId": assetId,
                "senderDataAvailabilityMode": senderDataAvailabilityMode,
                "receiverDataAvailabilityMode": receiverDataAvailabilityMode,
                "amount": amount,
                "tokenId": tokenId,
                "mintingBlob": mintingBlob,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    receiverDataAvailabilityMode: 'DataAvailabilityModes'
    amount: MetaOapg.properties.amount
    senderUserId: MetaOapg.properties.senderUserId
    assetId: MetaOapg.properties.assetId
    senderDataAvailabilityMode: 'DataAvailabilityModes'
    receiverUserId: MetaOapg.properties.receiverUserId
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["receiverDataAvailabilityMode"]) -> 'DataAvailabilityModes': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["senderUserId"]) -> MetaOapg.properties.senderUserId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assetId"]) -> MetaOapg.properties.assetId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["senderDataAvailabilityMode"]) -> 'DataAvailabilityModes': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["receiverUserId"]) -> MetaOapg.properties.receiverUserId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tokenId"]) -> MetaOapg.properties.tokenId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mintingBlob"]) -> MetaOapg.properties.mintingBlob: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["receiverDataAvailabilityMode"], typing_extensions.Literal["amount"], typing_extensions.Literal["senderUserId"], typing_extensions.Literal["assetId"], typing_extensions.Literal["senderDataAvailabilityMode"], typing_extensions.Literal["receiverUserId"], typing_extensions.Literal["tokenId"], typing_extensions.Literal["mintingBlob"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["receiverDataAvailabilityMode"]) -> 'DataAvailabilityModes': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["amount"]) -> MetaOapg.properties.amount: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["senderUserId"]) -> MetaOapg.properties.senderUserId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assetId"]) -> MetaOapg.properties.assetId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["senderDataAvailabilityMode"]) -> 'DataAvailabilityModes': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["receiverUserId"]) -> MetaOapg.properties.receiverUserId: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tokenId"]) -> typing.Union[MetaOapg.properties.tokenId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mintingBlob"]) -> typing.Union[MetaOapg.properties.mintingBlob, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["receiverDataAvailabilityMode"], typing_extensions.Literal["amount"], typing_extensions.Literal["senderUserId"], typing_extensions.Literal["assetId"], typing_extensions.Literal["senderDataAvailabilityMode"], typing_extensions.Literal["receiverUserId"], typing_extensions.Literal["tokenId"], typing_extensions.Literal["mintingBlob"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        receiverDataAvailabilityMode: 'DataAvailabilityModes',
        amount: typing.Union[MetaOapg.properties.amount, str, ],
        senderUserId: typing.Union[MetaOapg.properties.senderUserId, str, uuid.UUID, ],
        assetId: typing.Union[MetaOapg.properties.assetId, str, uuid.UUID, ],
        senderDataAvailabilityMode: 'DataAvailabilityModes',
        receiverUserId: typing.Union[MetaOapg.properties.receiverUserId, str, uuid.UUID, ],
        tokenId: typing.Union[MetaOapg.properties.tokenId, None, str, schemas.Unset] = schemas.unset,
        mintingBlob: typing.Union[MetaOapg.properties.mintingBlob, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'TransferDetailsModel':
        return super().__new__(
            cls,
            *_args,
            receiverDataAvailabilityMode=receiverDataAvailabilityMode,
            amount=amount,
            senderUserId=senderUserId,
            assetId=assetId,
            senderDataAvailabilityMode=senderDataAvailabilityMode,
            receiverUserId=receiverUserId,
            tokenId=tokenId,
            mintingBlob=mintingBlob,
            _configuration=_configuration,
        )

from starkexpress_api.model.data_availability_modes import DataAvailabilityModes
