# coding: utf-8

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from starkexpress_api import schemas  # noqa: F401


class WithdrawDetailsDto(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """


    class MetaOapg:
        
        class properties:
        
            @staticmethod
            def vault() -> typing.Type['VaultDto']:
                return VaultDto
            
            
            class operatorContractAddress(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'hex'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'operatorContractAddress':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class withdrawFunction(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'string'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'withdrawFunction':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class starkKey(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'hex'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'starkKey':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class assetType(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'hex'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'assetType':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class tokenId(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'hex'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'tokenId':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            
            
            class mintingBlob(
                schemas.StrBase,
                schemas.NoneBase,
                schemas.Schema,
                schemas.NoneStrMixin
            ):
            
            
                class MetaOapg:
                    format = 'hex'
            
            
                def __new__(
                    cls,
                    *_args: typing.Union[None, str, ],
                    _configuration: typing.Optional[schemas.Configuration] = None,
                ) -> 'mintingBlob':
                    return super().__new__(
                        cls,
                        *_args,
                        _configuration=_configuration,
                    )
            __annotations__ = {
                "vault": vault,
                "operatorContractAddress": operatorContractAddress,
                "withdrawFunction": withdrawFunction,
                "starkKey": starkKey,
                "assetType": assetType,
                "tokenId": tokenId,
                "mintingBlob": mintingBlob,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["vault"]) -> 'VaultDto': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["operatorContractAddress"]) -> MetaOapg.properties.operatorContractAddress: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["withdrawFunction"]) -> MetaOapg.properties.withdrawFunction: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["starkKey"]) -> MetaOapg.properties.starkKey: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["assetType"]) -> MetaOapg.properties.assetType: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["tokenId"]) -> MetaOapg.properties.tokenId: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["mintingBlob"]) -> MetaOapg.properties.mintingBlob: ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["vault"], typing_extensions.Literal["operatorContractAddress"], typing_extensions.Literal["withdrawFunction"], typing_extensions.Literal["starkKey"], typing_extensions.Literal["assetType"], typing_extensions.Literal["tokenId"], typing_extensions.Literal["mintingBlob"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["vault"]) -> typing.Union['VaultDto', schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["operatorContractAddress"]) -> typing.Union[MetaOapg.properties.operatorContractAddress, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["withdrawFunction"]) -> typing.Union[MetaOapg.properties.withdrawFunction, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["starkKey"]) -> typing.Union[MetaOapg.properties.starkKey, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["assetType"]) -> typing.Union[MetaOapg.properties.assetType, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["tokenId"]) -> typing.Union[MetaOapg.properties.tokenId, schemas.Unset]: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["mintingBlob"]) -> typing.Union[MetaOapg.properties.mintingBlob, schemas.Unset]: ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["vault"], typing_extensions.Literal["operatorContractAddress"], typing_extensions.Literal["withdrawFunction"], typing_extensions.Literal["starkKey"], typing_extensions.Literal["assetType"], typing_extensions.Literal["tokenId"], typing_extensions.Literal["mintingBlob"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        vault: typing.Union['VaultDto', schemas.Unset] = schemas.unset,
        operatorContractAddress: typing.Union[MetaOapg.properties.operatorContractAddress, None, str, schemas.Unset] = schemas.unset,
        withdrawFunction: typing.Union[MetaOapg.properties.withdrawFunction, None, str, schemas.Unset] = schemas.unset,
        starkKey: typing.Union[MetaOapg.properties.starkKey, None, str, schemas.Unset] = schemas.unset,
        assetType: typing.Union[MetaOapg.properties.assetType, None, str, schemas.Unset] = schemas.unset,
        tokenId: typing.Union[MetaOapg.properties.tokenId, None, str, schemas.Unset] = schemas.unset,
        mintingBlob: typing.Union[MetaOapg.properties.mintingBlob, None, str, schemas.Unset] = schemas.unset,
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'WithdrawDetailsDto':
        return super().__new__(
            cls,
            *_args,
            vault=vault,
            operatorContractAddress=operatorContractAddress,
            withdrawFunction=withdrawFunction,
            starkKey=starkKey,
            assetType=assetType,
            tokenId=tokenId,
            mintingBlob=mintingBlob,
            _configuration=_configuration,
        )

from starkexpress_api.model.vault_dto import VaultDto
