# coding: utf-8

# flake8: noqa

"""
    StarkExpress API Docs

    An API for the StarkExpress platform.  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "0.0.1"

# import ApiClient
from starkexpress_api.api_client import ApiClient

# import Configuration
from starkexpress_api.configuration import Configuration

# import exceptions
from starkexpress_api.exceptions import OpenApiException
from starkexpress_api.exceptions import ApiAttributeError
from starkexpress_api.exceptions import ApiTypeError
from starkexpress_api.exceptions import ApiValueError
from starkexpress_api.exceptions import ApiKeyError
from starkexpress_api.exceptions import ApiException
